# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

name: phd_ph4-02_pypsa-eur_large
channels:
  - conda-forge
  - bioconda
  - http://conda.anaconda.org/gurobi
dependencies:
  - python>=3.8
  - pip

  - pypsa>=0.19.1
  - atlite>=0.2.6
  - dask

  # Dependencies of the workflow itself
  - xlrd
  - openpyxl
  - scikit-learn
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - yaml
  - pytables
  - lxml
  - powerplantmatching>=0.5.3
  - numpy
  - pandas
  - geopandas>=0.11.0
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely
  - progressbar2
  - pyomo
  - matplotlib
  - proj
  - fiona <= 1.18.20  # Till issue https://github.com/Toblerity/Fiona/issues/1085 is not solved
  - country_converter

  # Keep in conda environment when calling ipython
  - ipython

  # GIS dependencies:
  - cartopy
  - descartes
  - rasterio<=1.2.9  # 1.2.10 creates error https://github.com/PyPSA/atlite/issues/238

  # PyPSA-Eur-Sec Dependencies
  - geopy
  - tqdm
  - pytz
  - tabula-py

  # # Solvers:
  # - ipopt
  # - glpk
  - gurobi >= 9

  # My packages
  - matplotlib>=3.3
  - notebook
  - jupyter
  - plotly
  - dill


  - pip:
    - vresutils>=0.3.1
    - tsam>=1.1.0
    - modin>=0.8
    - cdsapi
